import { Client, CompanyProfile, CurrencyConfig, Document, Item, ProductList, StaffUser } from './types';

export const INITIAL_CURRENCIES: CurrencyConfig[] = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', exchangeRate: 1.0 },
  { code: 'USD', symbol: '$', name: 'US Dollar', exchangeRate: 0.012 },
  { code: 'EUR', symbol: '€', name: 'Euro', exchangeRate: 0.011 },
  { code: 'GBP', symbol: '£', name: 'British Pound', exchangeRate: 0.0094 },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham', exchangeRate: 0.044 },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', exchangeRate: 0.016 },
  { code: 'AUD', symbol: 'AU$', name: 'Australian Dollar', exchangeRate: 0.018 },
  { code: 'SGD', symbol: 'SG$', name: 'Singapore Dollar', exchangeRate: 0.016 },
];

export const INITIAL_COMPANIES: CompanyProfile[] = [
  {
    id: 'comp-1',
    name: 'My Company',
    taxId: '',
    logoUrl: '',
    email: '',
    phone: '',
    address: '',
    city: '',
    country: '',
    website: '',
    bankDetails: {
      accountName: '',
      accountNumber: '',
      bankName: '',
      ifscSwift: '',
      upiId: '',
      qrCodeText: '',
    },
    defaultCurrency: 'INR',
    defaultTaxType: 'gst',
    defaultTaxRate: 18,
    isGstInterState: false,
    invoicePrefix: 'INV-',
    proformaPrefix: 'PI-',
    challanPrefix: 'DC-',
    terms: '1. Payment is due within 15 days of invoice date.\n2. Please mention the invoice number in the payment reference.\n3. Goods once sold are not returnable without prior authorization.',
    stampUrl: '',
    signatureUrl: '',
    authorizedSignatoryName: 'Authorized Signatory',
    authorizedSignatoryDesignation: 'Director',
    defaultDispatchAddress: {
      enabled: false,
      name: '',
      address: '',
      city: '',
      state: '',
      stateCode: '',
      pincode: '',
      phone: '',
      taxId: '',
    },
  },
];

export const INITIAL_COMPANY: CompanyProfile = INITIAL_COMPANIES[0];

export const INITIAL_PRODUCT_LISTS: ProductList[] = [
  {
    id: 'pl-services',
    name: 'Consulting & IT Services',
    description: 'Professional technical consulting, development, and support contracts',
    currency: 'INR',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isDefault: true,
  },
  {
    id: 'pl-hardware',
    name: 'Hardware & Networking Equipment',
    description: 'Computers, network switches, peripherals, and industrial parts',
    currency: 'INR',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item-1',
    name: 'Web Application Development',
    sku: 'SRV-DEV-01',
    description: 'Custom full-stack web application development and cloud architecture',
    hsnCode: '998314',
    unit: 'Hours',
    unitPrice: 2500,
    purchasePrice: 1500,
    taxRate: 18,
    category: 'Services',
    stockQuantity: 999,
    productListIds: ['pl-services'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-2',
    name: 'Enterprise IT Consulting',
    sku: 'SRV-CNS-02',
    description: 'Strategic IT architecture planning, security audit, and advisory',
    hsnCode: '998311',
    unit: 'Hours',
    unitPrice: 3500,
    purchasePrice: 2000,
    taxRate: 18,
    category: 'Services',
    stockQuantity: 999,
    productListIds: ['pl-services'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-3',
    name: 'Annual Maintenance Contract (AMC)',
    sku: 'SRV-AMC-03',
    description: 'Comprehensive software and infrastructure maintenance with 24/7 SLA',
    hsnCode: '998713',
    unit: 'Month',
    unitPrice: 15000,
    purchasePrice: 8000,
    taxRate: 18,
    category: 'Services',
    stockQuantity: 999,
    productListIds: ['pl-services'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-4',
    name: 'Managed Gigabit Switch 24-Port',
    sku: 'HW-SW-24P',
    description: 'Layer 2+ 24-port PoE Gigabit Enterprise Network Switch',
    hsnCode: '851762',
    unit: 'Unit',
    unitPrice: 18500,
    purchasePrice: 13500,
    taxRate: 18,
    category: 'Hardware',
    stockQuantity: 45,
    productListIds: ['pl-hardware'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-5',
    name: 'Industrial Microcontroller Board',
    sku: 'HW-MCU-10',
    description: 'Embedded industrial controller board with optocoupler isolation',
    hsnCode: '847130',
    unit: 'Pcs',
    unitPrice: 4200,
    purchasePrice: 2800,
    taxRate: 18,
    category: 'Hardware',
    stockQuantity: 120,
    productListIds: ['pl-hardware'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'item-6',
    name: 'Fiber Optic Patch Cord (10m Duplex)',
    sku: 'HW-FIB-10M',
    description: 'LC-LC Single Mode Duplex Fiber Optic Patch Cable',
    hsnCode: '854470',
    unit: 'Pcs',
    unitPrice: 650,
    purchasePrice: 350,
    taxRate: 18,
    category: 'Hardware',
    stockQuantity: 300,
    productListIds: ['pl-hardware'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'user-admin',
    name: 'Administrator',
    email: 'lpsunilkumar8@gmail.com',
    role: 'admin',
    avatarColor: 'bg-indigo-600',
    password: 'admin',
    pin: '1234',
    phone: '',
    department: 'Executive Leadership',
    status: 'active',
    createdAt: new Date().toISOString().split('T')[0],
  },
];

export const INITIAL_CLIENTS: Client[] = [];

export const INITIAL_DOCUMENTS: Document[] = [];
