import { Client, CompanyProfile, CurrencyConfig, Document, Item, ProductList, StaffUser } from './types';

export const INITIAL_CURRENCIES: CurrencyConfig[] = [
  { code: 'USD', symbol: '$', name: 'US Dollar', exchangeRate: 1.0 },
  { code: 'EUR', symbol: '€', name: 'Euro', exchangeRate: 0.92 },
  { code: 'GBP', symbol: '£', name: 'British Pound', exchangeRate: 0.78 },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', exchangeRate: 83.5 },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham', exchangeRate: 3.67 },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', exchangeRate: 1.36 },
  { code: 'AUD', symbol: 'AU$', name: 'Australian Dollar', exchangeRate: 1.52 },
  { code: 'SGD', symbol: 'SG$', name: 'Singapore Dollar', exchangeRate: 1.34 },
];

export const INITIAL_COMPANIES: CompanyProfile[] = [
  {
    id: 'comp-1',
    name: 'Apex Global Technologies & Logistics',
    taxId: '27AAACA9988Z1Z5',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=160&auto=format&fit=crop&q=80',
    email: 'billing@apexglobal.tech',
    phone: '+1 (555) 382-9900',
    address: 'Suite 400, 100 Enterprise Way',
    city: 'San Francisco, CA 94105',
    country: 'United States',
    website: 'https://apexglobal.tech',
    bankDetails: {
      accountName: 'Apex Global Technologies Inc.',
      accountNumber: '987654321045',
      bankName: 'Silicon Valley Commercial Bank',
      ifscSwift: 'SVCBUS33XXX',
      upiId: 'apexglobal@okhdfcbank',
      qrCodeText: 'upi://pay?pa=apexglobal@okhdfcbank&pn=ApexGlobal&cu=INR',
    },
    defaultCurrency: 'USD',
    defaultTaxType: 'gst',
    defaultTaxRate: 18,
    isGstInterState: false,
    invoicePrefix: 'INV-2026-',
    proformaPrefix: 'PI-2026-',
    challanPrefix: 'DC-2026-',
    terms: '1. Payment is due within 15 days of invoice date.\n2. Overdue payments are subject to a 1.5% monthly financing charge.\n3. Goods once sold will not be returned unless damaged during transit.\n4. Subject to San Francisco jurisdiction.',
    invoiceTheme: 'modern-indigo',
    proformaTheme: 'amber-quartz',
    challanTheme: 'teal-logistics',
  },
  {
    id: 'comp-2',
    name: 'BlueStar Global Logistics & Forwarding Pvt Ltd',
    taxId: '07AABCB2234P1Z3',
    logoUrl: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=160&auto=format&fit=crop&q=80',
    email: 'operations@bluestarlogistics.com',
    phone: '+91 11 4982 3000',
    address: 'Cargo Complex, Terminal 3 Road, Aerocity',
    city: 'New Delhi 110037',
    country: 'India',
    website: 'https://bluestarlogistics.com',
    bankDetails: {
      accountName: 'BlueStar Global Logistics & Forwarding Pvt Ltd',
      accountNumber: '50200029381023',
      bankName: 'HDFC Bank Ltd, Aerocity Branch',
      ifscSwift: 'HDFC0001234',
      upiId: 'bluestar@hdfcbank',
      qrCodeText: 'upi://pay?pa=bluestar@hdfcbank&pn=BlueStarLogistics&cu=INR',
    },
    defaultCurrency: 'INR',
    defaultTaxType: 'gst',
    defaultTaxRate: 18,
    isGstInterState: false,
    invoicePrefix: 'BS-INV-26-',
    proformaPrefix: 'BS-PI-26-',
    challanPrefix: 'BS-DC-26-',
    terms: '1. Standard freight terms apply.\n2. Demurrage and detention charges extra after free period.\n3. Subject to Delhi jurisdiction.',
    invoiceTheme: 'classic-corporate',
    proformaTheme: 'royal-navy',
    challanTheme: 'industrial-steel',
  },
];

export const INITIAL_COMPANY: CompanyProfile = INITIAL_COMPANIES[0];

export const INITIAL_PRODUCT_LISTS: ProductList[] = [
  {
    id: 'plist-1',
    name: 'Standard Enterprise Catalog',
    description: 'General billing catalog for standard software subscriptions, licenses, and core hardware.',
    companyId: 'comp-1',
    currency: 'USD',
    isDefault: true,
    itemIds: ['item-master-1', 'item-master-2', 'item-master-3', 'item-master-4', 'item-master-6'],
    createdAt: '2026-01-01',
    updatedAt: '2026-01-01',
  },
  {
    id: 'plist-2',
    name: 'Wholesale & Volume Price List',
    description: 'Discounted wholesale tier pricing for bulk distributors and B2B corporate partners.',
    companyId: 'comp-1',
    currency: 'USD',
    isDefault: false,
    itemIds: ['item-master-3', 'item-master-4'],
    createdAt: '2026-01-15',
    updatedAt: '2026-01-15',
  },
  {
    id: 'plist-3',
    name: 'IT Services & Retainers',
    description: 'Hourly rates, SLA maintenance plans, and engineering consulting engagements.',
    companyId: 'comp-1',
    currency: 'USD',
    isDefault: false,
    itemIds: ['item-master-2', 'item-master-6'],
    createdAt: '2026-01-20',
    updatedAt: '2026-01-20',
  },
  {
    id: 'plist-4',
    name: 'Logistics & Cargo Forwarding Tariff',
    description: 'Freight forwarding, dispatch handling, customs clearance, and courier services.',
    companyId: 'comp-2',
    currency: 'INR',
    isDefault: true,
    itemIds: ['item-master-5'],
    createdAt: '2026-02-01',
    updatedAt: '2026-02-01',
  },
];

export const INITIAL_ITEMS: Item[] = [
  {
    id: 'item-master-1',
    name: 'Enterprise Cloud ERP Platform',
    description: 'Cloud-based multi-tenant ERP platform subscription with automated financial ledger & tax reporting.',
    hsnCode: '998313',
    unit: 'License',
    unitPrice: 5000,
    purchasePrice: 2800,
    taxRate: 18,
    category: 'Software',
    stockQuantity: 100,
    companyId: 'comp-1',
    productListIds: ['plist-1'],
    createdAt: '2026-01-10',
  },
  {
    id: 'item-master-2',
    name: 'Dedicated Implementation & Security Sprint',
    description: 'Professional engineering sprint for SSO setup, custom API integration, and database migration.',
    hsnCode: '998314',
    unit: 'Hours',
    unitPrice: 150,
    purchasePrice: 90,
    taxRate: 18,
    category: 'Services',
    stockQuantity: 500,
    companyId: 'comp-1',
    productListIds: ['plist-1', 'plist-3'],
    createdAt: '2026-01-15',
  },
  {
    id: 'item-master-3',
    name: 'IoT Warehouse Tracking Hub (Gen 4)',
    description: 'Industrial GPS & BLE telemetry sensor gateway with IP67 weatherproof enclosure.',
    hsnCode: '851762',
    unit: 'Units',
    unitPrice: 1200,
    purchasePrice: 750,
    taxRate: 18,
    category: 'Hardware',
    stockQuantity: 45,
    companyId: 'comp-1',
    productListIds: ['plist-1', 'plist-2'],
    createdAt: '2026-02-01',
  },
  {
    id: 'item-master-4',
    name: 'Industrial Smart Barcode Scanners & Docking Cradles',
    description: '2D long-range wireless rugged handheld imager with charging cradle and battery pack.',
    hsnCode: '847160',
    unit: 'Sets',
    unitPrice: 8500,
    purchasePrice: 5800,
    taxRate: 18,
    category: 'Hardware',
    stockQuantity: 28,
    companyId: 'comp-1',
    productListIds: ['plist-1', 'plist-2'],
    createdAt: '2026-02-10',
  },
  {
    id: 'item-master-5',
    name: 'International Air Freight & Handling',
    description: 'Priority airport-to-airport customs cleared freight forwarding with temperature monitoring.',
    hsnCode: '996519',
    unit: 'Shipment',
    unitPrice: 1800,
    purchasePrice: 1200,
    taxRate: 18,
    category: 'Logistics',
    stockQuantity: 999,
    companyId: 'comp-2',
    productListIds: ['plist-4'],
    createdAt: '2026-02-12',
  },
  {
    id: 'item-master-6',
    name: 'Annual Cloud Maintenance & Support SLA',
    description: '24/7 dedicated site reliability engineering tier-1 SLA and emergency hotfix turnaround.',
    hsnCode: '998315',
    unit: 'Month',
    unitPrice: 800,
    purchasePrice: 400,
    taxRate: 18,
    category: 'Services',
    stockQuantity: 200,
    companyId: 'comp-1',
    productListIds: ['plist-1', 'plist-3'],
    createdAt: '2026-02-15',
  },
  {
    id: 'item-master-7',
    name: 'Thermal Shipping Label Rolls (4x6 inch, Pack of 10)',
    description: 'Direct thermal barcode transfer labels with ultra-strong adhesive for dispatch packages.',
    hsnCode: '482110',
    unit: 'Box',
    unitPrice: 450,
    purchasePrice: 280,
    taxRate: 12,
    category: 'Consumables',
    stockQuantity: 180,
    companyId: 'comp-2',
    productListIds: ['plist-4'],
    createdAt: '2026-02-25',
  },
];

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'user-admin',
    name: 'Sunil Kumar',
    email: 'lpsunilkumar8@gmail.com',
    role: 'admin',
    avatarColor: 'bg-indigo-600',
    password: 'admin123',
    pin: '1234',
    phone: '+1 (555) 382-9901',
    department: 'Executive Leadership',
    status: 'active',
    createdAt: '2026-01-01',
  },
  {
    id: 'user-mgr',
    name: 'Sarah Jenkins',
    email: 'sarah.j@apexglobal.tech',
    role: 'manager',
    avatarColor: 'bg-emerald-600',
    password: 'manager123',
    pin: '2345',
    phone: '+1 (555) 382-9902',
    department: 'Finance & Billing Operations',
    status: 'active',
    createdAt: '2026-01-05',
  },
  {
    id: 'user-staff',
    name: 'David Chen',
    email: 'david.c@apexglobal.tech',
    role: 'staff',
    avatarColor: 'bg-amber-600',
    password: 'staff123',
    pin: '3456',
    phone: '+1 (555) 382-9903',
    department: 'Enterprise Sales & Logistics',
    status: 'active',
    createdAt: '2026-01-10',
  },
  {
    id: 'user-audit',
    name: 'Emily Watson',
    email: 'emily.w@apexglobal.tech',
    role: 'auditor',
    avatarColor: 'bg-violet-600',
    password: 'audit123',
    pin: '4567',
    phone: '+1 (555) 382-9904',
    department: 'Statutory & Tax Compliance',
    status: 'active',
    createdAt: '2026-01-15',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'Marcus Vance',
    company: 'Nexus Dynamics Corp.',
    email: 'marcus.v@nexusdynamics.io',
    phone: '+1 (555) 723-9910',
    address: '450 Silicon Blvd, Suite 210, San Jose, CA',
    city: 'San Jose',
    country: 'USA',
    taxId: 'US-EIN-94-3829102',
    currency: 'USD',
    notes: 'Key enterprise account. Net 30 payment terms.',
    totalBilled: 14500,
    outstandingBalance: 3200,
    createdAt: '2026-01-15',
  },
  {
    id: 'client-2',
    name: 'Priya Sharma',
    company: 'Zenith Logistics & Supply Pvt Ltd',
    email: 'accounts@zenithlogistics.in',
    phone: '+91 98201 44521',
    address: 'Tech Park Zone 3, Outer Ring Road, Bengaluru',
    city: 'Bengaluru',
    country: 'India',
    taxId: '29ABCDE1234F1Z5',
    currency: 'INR',
    notes: 'Requires delivery challan dispatch with every equipment lot.',
    totalBilled: 685000,
    outstandingBalance: 125000,
    createdAt: '2026-02-01',
  },
  {
    id: 'client-3',
    name: 'Elena Rostova',
    company: 'Nordic Cloud Systems AB',
    email: 'e.rostova@nordiccloud.se',
    phone: '+46 8 123 4567',
    address: 'Kungsgatan 14, 111 43 Stockholm',
    city: 'Stockholm',
    country: 'Sweden',
    taxId: 'SE556012345601',
    currency: 'EUR',
    notes: 'Annual cloud consulting contracts.',
    totalBilled: 9400,
    outstandingBalance: 0,
    createdAt: '2026-01-20',
  },
  {
    id: 'client-4',
    name: 'Tariq Al-Mansoor',
    company: 'Gulf Horizon Trading LLC',
    email: 'tariq@gulfhorizon.ae',
    phone: '+971 4 398 2210',
    address: 'Business Bay Tower 2, Level 18, Dubai',
    city: 'Dubai',
    country: 'UAE',
    taxId: 'TRN-100293848100003',
    currency: 'AED',
    notes: 'Export transactions with zero VAT rate.',
    totalBilled: 42000,
    outstandingBalance: 15500,
    createdAt: '2026-02-12',
  },
];

export const INITIAL_DOCUMENTS: Document[] = [
  {
    id: 'doc-1',
    type: 'invoice',
    documentNumber: 'INV-2026-001',
    date: '2026-08-10',
    dueDate: '2026-08-25',
    clientId: 'client-1',
    clientName: 'Marcus Vance',
    clientCompany: 'Nexus Dynamics Corp.',
    clientEmail: 'marcus.v@nexusdynamics.io',
    clientPhone: '+1 (555) 723-9910',
    clientAddress: '450 Silicon Blvd, Suite 210, San Jose, CA',
    clientTaxId: 'US-EIN-94-3829102',
    currency: 'USD',
    taxType: 'sales_tax',
    taxRate: 8.5,
    items: [
      {
        id: 'item-1',
        description: 'Enterprise Cloud ERP Platform - Annual License',
        hsnCode: '998313',
        quantity: 1,
        unit: 'License',
        unitPrice: 5000,
        taxRate: 8.5,
        discount: 500,
        amount: 4500,
        taxAmount: 382.5,
        total: 4882.5,
      },
      {
        id: 'item-2',
        description: 'Dedicated Implementation & Security Setup',
        hsnCode: '998314',
        quantity: 20,
        unit: 'Hours',
        unitPrice: 150,
        taxRate: 8.5,
        discount: 0,
        amount: 3000,
        taxAmount: 255,
        total: 3255,
      },
    ],
    subtotal: 7500,
    discountTotal: 500,
    taxAmount: 637.5,
    shippingCharges: 0,
    grandTotal: 8137.5,
    status: 'partial',
    paidAmount: 5000,
    payments: [
      {
        id: 'pay-1',
        date: '2026-08-18',
        amount: 5000,
        method: 'bank_transfer',
        reference: 'WIRE-9923841',
        notes: 'Initial 60% deposit received',
        recordedBy: 'Sunil Kumar',
      },
    ],
    notes: 'Thank you for your business. Dedicated support engineer assigned.',
    terms: 'Payment due within 15 days of issue.',
    remindersSent: [
      {
        id: 'rem-1',
        date: '2026-08-28',
        channel: 'email',
        templateName: 'Overdue Friendly Notice',
        sentTo: 'marcus.v@nexusdynamics.io',
      },
    ],
    createdAt: '2026-08-10T10:00:00Z',
    createdBy: 'Sunil Kumar',
  },
  {
    id: 'doc-2',
    type: 'proforma',
    documentNumber: 'PI-2026-001',
    date: '2026-08-22',
    dueDate: '2026-09-10',
    clientId: 'client-4',
    clientName: 'Tariq Al-Mansoor',
    clientCompany: 'Gulf Horizon Trading LLC',
    clientEmail: 'tariq@gulfhorizon.ae',
    clientPhone: '+971 4 398 2210',
    clientAddress: 'Business Bay Tower 2, Level 18, Dubai',
    clientTaxId: 'TRN-100293848100003',
    currency: 'AED',
    taxType: 'vat',
    taxRate: 5,
    items: [
      {
        id: 'item-3',
        description: 'IoT Warehouse Tracking Hubs (Gen 4)',
        hsnCode: '851762',
        quantity: 10,
        unit: 'Units',
        unitPrice: 1200,
        taxRate: 5,
        discount: 500,
        amount: 11500,
        taxAmount: 575,
        total: 12075,
      },
      {
        id: 'item-4',
        description: 'International Air Freight & Handling',
        hsnCode: '996519',
        quantity: 1,
        unit: 'Shipment',
        unitPrice: 1800,
        taxRate: 5,
        discount: 0,
        amount: 1800,
        taxAmount: 90,
        total: 1890,
      },
    ],
    subtotal: 13300,
    discountTotal: 500,
    taxAmount: 665,
    shippingCharges: 250,
    grandTotal: 14215,
    status: 'unpaid',
    paidAmount: 0,
    payments: [],
    notes: 'Proforma valid for 30 calendar days. Shipment dispatched post 100% advance receipt.',
    terms: 'Goods manufactured to specifications. 1-year replacement warranty included.',
    remindersSent: [],
    createdAt: '2026-08-22T14:30:00Z',
    createdBy: 'David Chen',
  },
  {
    id: 'doc-3',
    type: 'challan',
    documentNumber: 'DC-2026-001',
    date: '2026-08-26',
    dueDate: '2026-09-05',
    clientId: 'client-2',
    clientName: 'Priya Sharma',
    clientCompany: 'Zenith Logistics & Supply Pvt Ltd',
    clientEmail: 'accounts@zenithlogistics.in',
    clientPhone: '+91 98201 44521',
    clientAddress: 'Tech Park Zone 3, Outer Ring Road, Bengaluru',
    clientTaxId: '29ABCDE1234F1Z5',
    currency: 'INR',
    taxType: 'gst',
    taxRate: 18,
    cgstAmount: 11250,
    sgstAmount: 11250,
    items: [
      {
        id: 'item-5',
        description: 'Industrial Smart Barcode Scanners & Docking Cradles',
        hsnCode: '847160',
        quantity: 15,
        unit: 'Sets',
        unitPrice: 8500,
        taxRate: 18,
        discount: 2500,
        amount: 125000,
        taxAmount: 22500,
        total: 147500,
      },
    ],
    subtotal: 125000,
    discountTotal: 2500,
    taxAmount: 22500,
    shippingCharges: 1500,
    grandTotal: 149000,
    status: 'paid',
    paidAmount: 149000,
    payments: [
      {
        id: 'pay-2',
        date: '2026-08-26',
        amount: 149000,
        method: 'upi',
        reference: 'UPI/2026082699210',
        notes: 'Full payment cleared on dispatch',
        recordedBy: 'Sarah Jenkins',
      },
    ],
    notes: 'Goods dispatched for on-site demonstration and warehouse integration testing.',
    terms: 'Returnable challan within 15 working days if not absorbed into permanent purchase.',
    challanDetails: {
      vehicleNo: 'KA-01-MJ-8822',
      dispatchDate: '2026-08-26',
      dispatchThrough: 'BlueDart Express Courier',
      deliveryNote: 'Lot #441 - Fragile Electronic Equipment',
      returnable: true,
      receivedBy: 'Warehouse Security / Inward Dept',
    },
    remindersSent: [],
    createdAt: '2026-08-26T09:15:00Z',
    createdBy: 'Sarah Jenkins',
  },
  {
    id: 'doc-4',
    type: 'invoice',
    documentNumber: 'INV-2026-002',
    date: '2026-08-01',
    dueDate: '2026-08-15',
    clientId: 'client-3',
    clientName: 'Elena Rostova',
    clientCompany: 'Nordic Cloud Systems AB',
    clientEmail: 'e.rostova@nordiccloud.se',
    clientPhone: '+46 8 123 4567',
    clientAddress: 'Kungsgatan 14, 111 43 Stockholm',
    clientTaxId: 'SE556012345601',
    currency: 'EUR',
    taxType: 'vat',
    taxRate: 0,
    items: [
      {
        id: 'item-6',
        description: 'DevOps Infrastructure Automation Sprint',
        hsnCode: '998315',
        quantity: 1,
        unit: 'Sprint',
        unitPrice: 4200,
        taxRate: 0,
        discount: 0,
        amount: 4200,
        taxAmount: 0,
        total: 4200,
      },
    ],
    subtotal: 4200,
    discountTotal: 0,
    taxAmount: 0,
    shippingCharges: 0,
    grandTotal: 4200,
    status: 'paid',
    paidAmount: 4200,
    payments: [
      {
        id: 'pay-3',
        date: '2026-08-12',
        amount: 4200,
        method: 'bank_transfer',
        reference: 'SEPA-2026-99321',
        notes: 'Full payment received via SEPA',
        recordedBy: 'Sunil Kumar',
      },
    ],
    notes: 'Zero-rated reverse charge B2B intra-EU supply of digital services.',
    terms: 'Thank you for choosing Apex Global.',
    remindersSent: [],
    createdAt: '2026-08-01T11:00:00Z',
    createdBy: 'Sunil Kumar',
  },
  {
    id: 'doc-5',
    type: 'invoice',
    documentNumber: 'INV-2026-003',
    date: '2026-08-15',
    dueDate: '2026-08-30',
    clientId: 'client-4',
    clientName: 'Tariq Al-Mansoor',
    clientCompany: 'Gulf Horizon Trading LLC',
    clientEmail: 'tariq@gulfhorizon.ae',
    clientPhone: '+971 4 398 2210',
    clientAddress: 'Business Bay Tower 2, Level 18, Dubai',
    clientTaxId: 'TRN-100293848100003',
    currency: 'USD',
    taxType: 'sales_tax',
    taxRate: 5,
    items: [
      {
        id: 'item-7',
        description: 'Logistics Analytics Software Custom Module',
        hsnCode: '998319',
        quantity: 1,
        unit: 'Module',
        unitPrice: 3500,
        taxRate: 5,
        discount: 200,
        amount: 3300,
        taxAmount: 165,
        total: 3465,
      },
    ],
    subtotal: 3300,
    discountTotal: 200,
    taxAmount: 165,
    shippingCharges: 0,
    grandTotal: 3465,
    status: 'overdue',
    paidAmount: 0,
    payments: [],
    notes: 'Past due notice sent.',
    terms: 'Subject to 1.5% late payment monthly penalty.',
    remindersSent: [
      {
        id: 'rem-2',
        date: '2026-08-31',
        channel: 'whatsapp',
        templateName: 'Friendly Overdue Reminder',
        sentTo: '+971 4 398 2210',
      },
    ],
    createdAt: '2026-08-15T08:00:00Z',
    createdBy: 'David Chen',
  },
];
